module Resource; end

require 'resource/base'
require 'resource/cron'
require 'resource/directory'
require 'resource/execute'
require 'resource/file'
require 'resource/gem'
require 'resource/git'
require 'resource/group'
require 'resource/hook'
require 'resource/link'
require 'resource/package'
require 'resource/remote_file'
require 'resource/service'
require 'resource/swap_release'
require 'resource/template'
require 'resource/user'
require 'resource/version'
